storage_dir: "PLACEHOLDER" # Path to the directory where heavy duty storage will be done, meant for large files like models and datasets
env_dir: "setup/.venv/" # Path to the virtual environment. If you have installed the venv in a different location, make sure to change this.
huggingface_repo_namespace: "DJ-Research" # The namespace (user or org) on the hub where the repo is located. Use this to sync large files
huggingface_repo_name: "PokemonRedRL" # The name of the repo on the hub. Use this to sync large files
